version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: 'rabbitmq:3.11.9-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - local_bridge
  postgres:
    container_name: postgres_container
    hostname: postgres_container
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./local_postgres_data:/data/postgres
      - ./db/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    command: postgres -c 'hba_file=/var/lib/postgresql/pg_hba.conf'
    ports:
      - '5432:5432'
    networks:
      - local_bridge
    restart: unless-stopped
  postgres-bp:
    container_name: postgres-bp_container
    hostname: postgres-bp_container
    build:
      context: './db/backup'
      dockerfile: Dockerfile
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - ./db/backup/backups:/backups
      - ./db/backup/pg_backup.config:/work/pg_backup.config
    networks:
      - local_bridge
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    hostname: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - local_bridge
    restart: unless-stopped
  price-updater:
    build:
      context: '../'
      dockerfile: abax-liquidator/actor.node.Dockerfile
    image: 'liquidation-node-actor'
    container_name: 'price-updater'
    hostname: 'price-updater'
    restart: always
    environment:
      ACTOR_TO_RUN: PRICE_UPDATER
    volumes:
      - './logs:/app/logs'
    env_file:
      - '.env.local.docker'
      - '.env.secret'
    networks:
      - local_bridge
  reservedata-chain-updater:
    build:
      context: '../'
      dockerfile: abax-liquidator/actor.node.Dockerfile
    image: 'liquidation-node-actor'
    container_name: 'reservedata-chain-updater'
    hostname: 'reservedata-chain-updater'
    restart: always
    environment:
      ACTOR_TO_RUN: RESERVE_DATA_CHAIN_UPDATER
    volumes:
      - './logs:/app/logs'
    env_file:
      - '.env.local.docker'
      - '.env.secret'
    networks:
      - local_bridge
  userdata-chain-updater:
    build:
      context: '../'
      dockerfile: abax-liquidator/actor.node.Dockerfile
    image: 'liquidation-node-actor'
    container_name: 'userdata-chain-updater'
    hostname: 'userdata-chain-updater'
    restart: always
    environment:
      ACTOR_TO_RUN: USER_DATA_CHAIN_UPDATER
    volumes:
      - './logs:/app/logs'
    env_file:
      - '.env.local.docker'
      - '.env.secret'
    networks:
      - local_bridge
  eventanalysis-ensurer:
    build:
      context: '../'
      dockerfile: abax-liquidator/actor.node.Dockerfile
    image: 'liquidation-node-actor'
    container_name: 'eventanalysis-ensurer'
    hostname: 'eventanalysis-ensurer'
    restart: always
    environment:
      ACTOR_TO_RUN: EVENT_ANALYZE_ENSURER
    volumes:
      - './logs:/app/logs'
    env_file:
      - '.env.local.docker'
      - '.env.secret'
    networks:
      - local_bridge
  event-listener:
    build:
      context: '../'
      dockerfile: abax-liquidator/actor.node.Dockerfile
    image: 'liquidation-node-actor'
    container_name: 'event-listener'
    hostname: 'event-listener'
    restart: always
    environment:
      ACTOR_TO_RUN: EVENT_LISTENER
    volumes:
      - './logs:/app/logs'
    env_file:
      - '.env.local.docker'
      - '.env.secret'
    networks:
      - local_bridge
  periodic-hf-updater:
    build:
      context: '../'
      dockerfile: abax-liquidator/actor.node.Dockerfile
    image: 'liquidation-node-actor'
    container_name: 'periodic-hf-updater'
    hostname: 'periodic-hf-updater'
    restart: always
    environment:
      ACTOR_TO_RUN: PERIODIC_HFUPDATER
      AMQP_URL: amqp://rabbitmq
    volumes:
      - './logs:/app/logs'
    env_file:
      - '.env.local.docker'
      - '.env.secret'
    networks:
      - local_bridge
  price-change-updater:
    build:
      context: '../'
      dockerfile: abax-liquidator/actor.node.Dockerfile
    image: 'liquidation-node-actor'
    container_name: 'price-change-updater'
    hostname: 'price-change-updater'
    restart: always
    environment:
      ACTOR_TO_RUN: PRICE_CHANGE_HFUPDATER
    volumes:
      - './logs:/app/logs'
    env_file:
      - '.env.local.docker'
      - '.env.secret'
    networks:
      - local_bridge
  liquidator:
    build:
      context: '../'
      dockerfile: abax-liquidator/actor.node.Dockerfile
    image: 'liquidation-node-actor'
    container_name: 'liquidator'
    hostname: 'liquidator'
    restart: always
    environment:
      ACTOR_TO_RUN: LIQUIDATOR
    volumes:
      - './logs:/app/logs'
    env_file:
      - '.env.local.docker'
      - '.env.secret'
    networks:
      - local_bridge

networks:
  local_bridge:
    driver: bridge
volumes:
  pgadmin:
