version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.11.9-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./local_postgres_data:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped
  postgres-bp:
    container_name: postgres-bp_container
    build:
      context: './db/backup'
      dockerfile: Dockerfile
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - ./db/backup/backups:/backups
      - ./db/backup/pg_backup.config:/work/pg_backup.config
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres
    restart: unless-stopped
  price-updater:
    build:
      context: '../'
      dockerfile: abax-liquidator/actor.node.Dockerfile
    image: 'price-updater'
    container_name: 'price-updater'
    restart: always
    environment:
      ACTOR_TO_RUN: PRICE_UPDATER
    volumes:
      - './logs:/app/logs'
    env_file:
      - '.env.local.docker'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
volumes:
  pgadmin:
