export const AMQP_URL = process.env.AMQP_URL ?? 'amqp://localhost:5672';
export const LIQUIDATION_QUEUE_NAME = 'LIQUIDATION_QUEUE';
export const USER_DATA_QUEUE_NAME = 'USER_DATA_QUEUE_NAME';
export const LIQUIDATION_EXCHANGE = 'LIQUIDATION_EXCHANGE';
export const LIQUIDATION_ROUTING_KEY = 'LIQUIDATION_ROUTING_KEY';
export const USER_DATA_ROUTING_KEY = 'USER_DATA_ROUTING_KEY';
